// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9GJtrBPLzh9ICWWp3xwRFkqwvcfvp8rs',
    appId: '1:666773139798:web:9e873bf97002e665af26f7',
    messagingSenderId: '666773139798',
    projectId: 'easycoupon-3302c',
    authDomain: 'easycoupon-3302c.firebaseapp.com',
    storageBucket: 'easycoupon-3302c.appspot.com',
    measurementId: 'G-LBZ634FQXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOyhZ1PXC1Jo5_l-bh4NHCpoE0NMQ8twQ',
    appId: '1:666773139798:android:01900835a75a2936af26f7',
    messagingSenderId: '666773139798',
    projectId: 'easycoupon-3302c',
    storageBucket: 'easycoupon-3302c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2ThP39uF0RxP4FrpNMVDuV-DsgW0RpLM',
    appId: '1:666773139798:ios:b5a8548e2b0750eaaf26f7',
    messagingSenderId: '666773139798',
    projectId: 'easycoupon-3302c',
    storageBucket: 'easycoupon-3302c.appspot.com',
    iosBundleId: 'com.example.easycoupon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2ThP39uF0RxP4FrpNMVDuV-DsgW0RpLM',
    appId: '1:666773139798:ios:b5a8548e2b0750eaaf26f7',
    messagingSenderId: '666773139798',
    projectId: 'easycoupon-3302c',
    storageBucket: 'easycoupon-3302c.appspot.com',
    iosBundleId: 'com.example.easycoupon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9GJtrBPLzh9ICWWp3xwRFkqwvcfvp8rs',
    appId: '1:666773139798:web:430ff82527bd6bddaf26f7',
    messagingSenderId: '666773139798',
    projectId: 'easycoupon-3302c',
    authDomain: 'easycoupon-3302c.firebaseapp.com',
    storageBucket: 'easycoupon-3302c.appspot.com',
    measurementId: 'G-489HTYPN0H',
  );
}
